server:
  port: 8010


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:   #自己数据库的用户名
    password:   #自己数据库的密码
    url: jdbc:mysql://localhost:3306/coal_trading?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #coal_trading_platform coal_trading
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  resources:
    static-locations: clasaspath:static/

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: tb_
  configuration-properties:
    prefix: tb_ # 自定义sql中表名带前缀
image:
  config:
    type:
      - jpg
      - jpeg
      - png
    path: static/images/